version: "3.8"

services:
  frontend:
    networks:
      - rechtebank-network
      - proxy
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.rechtbank.rule=Host("${DOMAIN}")'
      - "traefik.http.routers.rechtbank.tls=true"
      - "traefik.http.routers.rechtbank.tls.certresolver=lets-encrypt"
      - "traefik.http.services.rechtbank.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
    name: proxy
